### ISSUE TITLE
io:HorizontalAwningIOComponent reports 0 as the current_position when it's fully opened

### ISSUE THREAD

**Issue by cdeharo** [iMicknl/ha-tahoma#103]
**Describe the bug**
The `current_position` of the `io:HorizontalAwningIOComponent` is always `0` but the `core:DeploymentState` is `100` when:
* Using the service `cover.open_cover`
* Setting the `100` position using the service `cover.set_cover_position`

Using the service `cover.set_cover_position` to establish the `99` position reports:
```yaml
current_position: 100
core:DeploymentState: 98
```

Using the service `cover.set_cover_position` to establish other positions, like `50` reports the correct `current_position` and the same `core:DeploymentState`.

Despite of having the `custom_components.tahoma: debug` configuration, no logs are registered during the reproduction of this bug.

**To Reproduce**
1. Send this request:
```yaml
service: cover.set_cover_position
data:
  entity_id: cover.myawning
  position: 100
```
2. The `current_position` attribute of the `cover.myawning` entity reports the value `0`
3. The slider in the GUI is in the `0` position.
4. The close button in the GUI is not enabled.

**Expected behavior**
The `current_position` attribute of the `cover.myawning` entity must report the value `100`. and the same with the slider in the GUI and the close button must be enabled when the awning is at full opening position.

**Environment**
 - **Home Assistant version**: 0.112.2
 - **Platform**: Somfy TaHoma 1.5 (custom component)

**Device:**
 - **Model**: PositionableHorizontalAwning by Somfy
 - **Type**: io:HorizontalAwningIOComponent
 - **Device details**: sorry, I can't access the `https://www.tahomalink.com/enduser-mobile-web/steer-html5-client/tahoma/` to get the details of the device. I'm using the same credentials that I use in this platform, but the web reports an error (maybe because I own a Connexoon and not a Tahoma).

**Additional context**
The problems with this awning started after a Connexoon firmware update originally reported in the [home-assistant/core issue #37291](https://github.com/home-assistant/core/issues/37291). I haven't managed to retrieve the firmware version in the Connexoon Terrace Android app.

**Comment by iMicknl** [comment]
The `current_position` offset around 95 is due to #112. 

The other part could be due to the reverse logic we have built-in for Horizontal Awnings after multiple user reports.. Is the open / close (and set position) exactly reversed with what you would expect?

Please note that 0 is closed in Home Assistant and 100 is fully open.

https://github.com/iMicknl/ha-tahoma/blob/dd3a5c67035e591429071439b818ca991dca6122/custom_components/tahoma/cover.py#L108-L137

**Comment by cdeharo** [comment]
>The other part could be due to the reverse logic we have built-in for Horizontal Awnings after multiple user reports.. Is the open / close (and set position) exactly reversed with what you would expect?

No, I don't experiment this reverse logic. When buttons are enabled (when the awning is not fully opened), the open and close buttons works fine and in the expected direction. The `set_position` also works as expected: opening and closing the awning to the desired position.

I think that this could be only a matter of the `current_position` value when the awning is fully opened. As you stated, a fully opened awning must be `100`, but it reports `0`. I think that this could be the reason behind the close button not being enabled only in this case. If you use the `set_position` service to fully open the awning (`100`), the awning opens to fully opened position, but it reports `0` as the `current_position`.

> The current_position offset around 95 is due to #112.
Ok, I've never detected this behaviour with the old integration, I will follow the issue. Thanks.

**Comment by iMicknl** [comment]
https://github.com/iMicknl/ha-tahoma/blob/dd3a5c67035e591429071439b818ca991dca6122/custom_components/tahoma/cover.py#L212-L232

Thanks for your detailed comments @cdeharo. It could be due to the `is_closed()` function not taking the Horizontal reverse into account.

**Comment by cdeharo** [comment]
I don't know if it has something to do with the horizontal reverse.

These are the attributes of the awning in fully opened state:
```yaml
current_position: 0
uiclass: Awning
widget: PositionableHorizontalAwning
type: io:HorizontalAwningIOComponent
rssi_level: 76
core:NameState: My Awning
core:PriorityLockTimerState: 0
core:StatusState: available
core:DiscreteRSSILevelState: normal
core:RSSILevelState: 76
core:DeploymentState: 100
core:OpenClosedState: open
friendly_name: Toldo salon
supported_features: 15
device_class: awning
```

The problem I see is with the `current_position` not matching the `core:DeploymentState` when its fully opened. 

Also, if I set the awning to an intermediate position, the buttons act as expected and the state (open or closed) always match the real state of the awning (in this example I set the awning to `42`):
```yaml
current_position: 42
uiclass: Awning
widget: PositionableHorizontalAwning
type: io:HorizontalAwningIOComponent
rssi_level: 82
core:NameState: My Awning
core:PriorityLockTimerState: 0
core:StatusState: available
core:DiscreteRSSILevelState: good
core:RSSILevelState: 82
core:DeploymentState: 42
core:OpenClosedState: open
friendly_name: Toldo salon
supported_features: 15
device_class: awning
```
