### ISSUE TITLE
Device trigger not supported in automation (for alarm control panel)

### ISSUE THREAD

**Issue by tofgun** [iMicknl/ha-tahoma#356]
I have created an automation : when the somfy protect alarm is armed night I want to do an automation. 

The problem is the automation based on a device trigger  is never launched : 
```
alias: Alarme Night ON Device
description: ''
trigger:
  - platform: device
    device_id: 0874d314802ed9f218b813a8acf8ebea
    domain: alarm_control_panel
    entity_id: alarm_control_panel.somfy_one_salon
    type: armed_night
condition: []
action:
  - device_id: 01e8270cf2cc3d50aa26b59f6e20c6c5
    domain: cover
    entity_id: cover.vr_bureau_2
    type: set_position
    position: 84
mode: single
```

The Automation based on a state trigger  is working properly : 

```
alias: Alarme Night ON State
description: ''
trigger:
  - platform: state
    entity_id: alarm_control_panel.somfy_one_salon
    attribute: 'myfox:AlarmStatusState'
    from: disarmed
    to: partial
condition: []
action:
  - device_id: 01e8270cf2cc3d50aa26b59f6e20c6c5
    domain: cover
    entity_id: cover.vr_bureau_2
    type: set_position
    position: 84
mode: single
```
